export MASTER_ADDR="localhost"
export MASTER_PORT=29504
export NCCL_P2P_DISABLE=1
export NCCL_IB_DISABLE=1
export TORCH_NCCL_BLOCKING_WAIT=1
export NCCL_DEBUG=INFO
export TORCH_DISTRIBUTED_DEBUG=DETAIL
export CUDA_LAUNCH_BLOCKING=1
export CUDA_VISIBLE_DEVICES=0

python train.py --config $1
